/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcostos_JavaCostos */

#ifndef _Included_libcostos_JavaCostos
#define _Included_libcostos_JavaCostos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcostos_JavaCostos
 * Method:    calcularCostoTotal
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_libcostos_JavaCostos_calcularCostoTotal
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     libcostos_JavaCostos
 * Method:    calcularCostoUnitario
 * Signature: (FI)F
 */
JNIEXPORT jfloat JNICALL Java_libcostos_JavaCostos_calcularCostoUnitario
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     libcostos_JavaCostos
 * Method:    calcularMargenGanancia
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_libcostos_JavaCostos_calcularMargenGanancia
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     libcostos_JavaCostos
 * Method:    calcularPrecioVenta
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_libcostos_JavaCostos_calcularPrecioVenta
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     libcostos_JavaCostos
 * Method:    generarJSONCostos
 * Signature: (FFFIF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcostos_JavaCostos_generarJSONCostos
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
